
export const homePageText = {
    introduction: `Me llamo Sam y estoy estudiando el grado superior de desarrollo de aplicaciones multiplataforma en el marco de una formación dual. Mis objetivos personales en esta formación son aprender y formarme el máximo posible para adaptarme a cualquier tarea que se ponga ante mí. Mi motivación inicial para estudiar esta formación fue mi intriga por el mundo de la programación, pero también porque me encanta estar en constante aprendizaje y creo que esta formación dual me permitirá crecer de manera muy efectiva. Escoger la formación dual fue una decisión muy consciente, puesto que me permite formarme al máximo en el mínimo tiempo posible. Desde que he empezado a estudiar este grado superior, me he sorprendido de cómo me gusta y he aprendido mucho sobre el desarrollo de aplicaciones multiplataforma, el que me ha motivado a continuar esforzándome para conseguir mis objetivos.`,
    experiencies: `Descubre algunas de las experiencias que he tenido a lo largo de mi carrera profesional. En esta sección, encontrarás información sobre mi paso por Bemen 3, donde realicé mis estudios y adquirí conocimientos fundamentales. También podrás conocer mi experiencia en Travelport, una empresa donde realicé prácticas y tuve la oportunidad de aplicar mis habilidades en un entorno laboral. Además, te presentaré algunos de los proyectos que he desarrollado por cuenta propia, mostrando mi iniciativa y pasión por la creación de soluciones innovadoras.`,
};

export const professionalProjectionPageText = {
    introduction: `Mi experiencia en la formación dual en el grado superior de desarrollo de aplicaciones multiplataforma ha sido extremadamente enriquecedora y cooperativa. Durante este período, he tenido la oportunidad de conocer a mucha gente y he tenido que trabajar en equipo para alcanzar los objetivos marcados. Uno de los puntos fuertes de esta formación dual ha sido la flexibilidad que me ha permitido la empresa colaboradora en cuanto al horario de trabajo, lo que me ha facilitado la conciliación del aprendizaje con otros ámbitos de mi vida personal. Además he aprendido sobre nuevos lenguajes de programación, metodologías de trabajo y otras técnicas de desarrollo de aplicaciones multiplataforma, lo que me ha permitido crecer a nivel profesional y ampliar mis conocimientos. En resumen, ha sido una experiencia altamente positiva que me ha permitido adquirir nuevas competencias y desarrollarme tanto a nivel personal como profesional.`,
    presentation: `Me llamo Sam y estoy estudiando el grado superior de desarrollo de aplicaciones multiplataforma en el marco de una formación dual. Mis objetivos personales en esta formación son aprender y formarme lo máximo posible para adaptarme a cualquier tarea que se ponga delante de mí. Mi motivación inicial para estudiar esta formación fue mi intriga por el mundo de la programación, pero también porque me encanta estar en constante aprendizaje y creo que esta formación dual me permitirá crecer de forma muy efectiva. Escoger la formación dual fue una decisión muy consciente, ya que me permite formarme al máximo en el menor tiempo posible. Desde que he empezado a estudiar este grado superior, me he sorprendido de cómo me gusta y he aprendido mucho sobre el desarrollo de aplicaciones multiplataforma, lo que me ha motivado a seguir esforzándome por conseguir mis objetivos. Mi formación dual empezó el 01/07/2022 y finalizará el 31/05/2023, con una duración total de 900 horas. Además, también realicé una FCT (formación en centros de trabajo) que tuvo una duración de 99 horas, y fue del 03/06/2022 al 30/06/2022.`,
}